---

- name: Ensure bash, git are the latest versions
  apt: name={{ item }} update_cache={{ update_apt_cache }} state=latest force=yes state=installed
  with_items:
    - bash
    - openssl
    - libssl-dev
    - libssl-doc
    - git
    - supervisor
  tags: packages

- apt_repository:
    repo: ppa:certbot/certbot
    state: present

- name: Install certbot
  apt: name=certbot update_cache={{ update_apt_cache }} force=yes state=installed
  tags: packages